de.cketti.safecontentresolver.ErrnoException extends java.lang.Exception
public final int errno
private final java.lang.String functionName
    public void <init>(java.lang.String, int)
    {
        de.cketti.safecontentresolver.ErrnoException r0;
        java.lang.String $r1;
        int $i0;

        r0 := @this: de.cketti.safecontentresolver.ErrnoException;

        $r1 := @parameter0: java.lang.String;

        $i0 := @parameter1: int;

        specialinvoke r0.<java.lang.Exception: void <init>()>();

        r0.<de.cketti.safecontentresolver.ErrnoException: java.lang.String functionName> = $r1;

        r0.<de.cketti.safecontentresolver.ErrnoException: int errno> = $i0;

        return;
    }
    public java.lang.String getMessage()
    {
        de.cketti.safecontentresolver.ErrnoException r0;
        java.lang.StringBuilder $r1;
        java.lang.String $r2;
        int $i0;

        r0 := @this: de.cketti.safecontentresolver.ErrnoException;

        $r1 = new java.lang.StringBuilder;

        specialinvoke $r1.<java.lang.StringBuilder: void <init>()>();

        $r2 = r0.<de.cketti.safecontentresolver.ErrnoException: java.lang.String functionName>;

        $r1 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r2);

        $r1 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" failed: ");

        $i0 = r0.<de.cketti.safecontentresolver.ErrnoException: int errno>;

        $r1 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i0);

        $r2 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.String toString()>();

        return $r2;
    }
