b.a.a.a.a.c.d extends java.util.concurrent.FutureTask
final b.a.a.a.a.c.a a
    void <init>(b.a.a.a.a.c.a, java.util.concurrent.Callable)
    {
        b.a.a.a.a.c.d r0;
        b.a.a.a.a.c.a $r1;
        java.util.concurrent.Callable $r2;

        r0 := @this: b.a.a.a.a.c.d;

        $r1 := @parameter0: b.a.a.a.a.c.a;

        $r2 := @parameter1: java.util.concurrent.Callable;

        r0.<b.a.a.a.a.c.d: b.a.a.a.a.c.a a> = $r1;

        specialinvoke r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }
    protected void done()
    {
        b.a.a.a.a.c.d r0;
        b.a.a.a.a.c.a $r1;
        java.lang.Object $r2;
        java.lang.InterruptedException $r3;
        java.util.concurrent.ExecutionException $r4;
        java.lang.RuntimeException $r5;
        java.lang.Throwable $r6;
        java.util.concurrent.CancellationException $r7;

        r0 := @this: b.a.a.a.a.c.d;

        $r1 = r0.<b.a.a.a.a.c.d: b.a.a.a.a.c.a a>;

     label1:
        $r2 = virtualinvoke r0.<b.a.a.a.a.c.d: java.lang.Object get()>();

        staticinvoke <b.a.a.a.a.c.a: void b(b.a.a.a.a.c.a,java.lang.Object)>($r1, $r2);

     label2:
        return;

     label3:
        $r3 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r3);

        return;

     label4:
        $r4 := @caughtexception;

        $r5 = new java.lang.RuntimeException;

        $r6 = virtualinvoke $r4.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r6);

        throw $r5;

     label5:
        $r7 := @caughtexception;

        $r1 = r0.<b.a.a.a.a.c.d: b.a.a.a.a.c.a a>;

        staticinvoke <b.a.a.a.a.c.a: void b(b.a.a.a.a.c.a,java.lang.Object)>($r1, null);

        return;

        catch java.lang.InterruptedException from label1 to label2 with label3;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label4;
        catch java.util.concurrent.CancellationException from label1 to label2 with label5;
    }
